baseURL = "https://c10n.net"
languageCode = "en"
title = "c10n"
theme = "hugo-coder"
defaultContentLanguage = "en"

[params]
  author = "Alan Christianson"
  description = "Solving problems slightly faster than I create them"
  keywords = "blog,developer,personal"
  info = ["Staff Software Engineer", "Infrastructure & Cloud"]
  colorScheme = "auto"
  hideColorSchemeToggle = false

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/alanc10n"

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Publications"
  weight = 2
  url = "publications/"

[[menu.main]]
  name = "Blog"
  weight = 3
  url = "posts/"
